name: Full build

description: Builds and tests

inputs:
  RELEASE_KEYSTORE_BASE64:
    description: "RELEASE_KEYSTORE_BASE64"
    required: false
    default: ""
  RELEASE_KEYSTORE_PASS:
    description: "RELEASE_KEYSTORE_PASS"
    required: false
    default: ""
  ENABLE_SIGNING:
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Need full history for git versioning

    - name: List files
      shell: bash
      run: ls

    - uses: actions/setup-dotnet@v4

    - name: Show .NET info
      shell: bash
      run: dotnet --info

    - name: Install .NET MAUI
      shell: bash
      run: dotnet workload install maui android wasm-tools

    - name: Test
      shell: bash
      run: dotnet test

    - name: Create keystore
      if: inputs.ENABLE_SIGNING == 'true'
      id: create_keystore
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: release.keystore
        encodedString: "${{ inputs.RELEASE_KEYSTORE_BASE64 }}"

    - name: Build for Android (signed)
      if: inputs.ENABLE_SIGNING == 'true'
      shell: bash
      run: >
        dotnet publish ./JournalApp/JournalApp.csproj -o publish -c:Release -f:net10.0-android
        -p:AndroidKeyStore=True
        -p:AndroidSigningKeyStore="${{ steps.create_keystore.outputs.filePath }}"
        -p:AndroidSigningStorePass="${{ inputs.RELEASE_KEYSTORE_PASS }}"
        -p:AndroidSigningKeyAlias="key"
        -p:AndroidSigningKeyPass="${{ inputs.RELEASE_KEYSTORE_PASS }}"

    - name: Build for Android (unsigned)
      if: inputs.ENABLE_SIGNING != 'true'
      shell: bash
      run: >
        dotnet publish ./JournalApp/JournalApp.csproj -o publish -c:Release -f:net10.0-android

    - name: List build output
      shell: bash
      run: ls publish
