name: Full build

description: Builds and tests

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Need full history for git versioning

    - uses: actions/setup-dotnet@v3
    
    - name: Show .NET info
      shell: bash
      run: dotnet --info

    - name: Install .NET MAUI
      shell: bash
      run: dotnet workload install maui android wasm-tools

    - name: Test
      shell: bash
      run: dotnet test

    - name: Create keystore
      id: create_keystore
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: release.keystore
        encodedString: "${{ secrets.RELEASE_KEYSTORE_BASE64 }}"

    - name: Build for Android
      shell: bash
      run: >
        dotnet publish JournalApp\JournalApp.csproj -o publish -c:Release -f:net8.0-android
        -p:AndroidKeyStore=True
        -p:AndroidSigningKeyStore="${{ steps.create_keystore.outputs.filePath }}"
        -p:AndroidSigningStorePass="${{ secrets.RELEASE_KEYSTORE_PASS }}"
        -p:AndroidSigningKeyAlias="key"
        -p:AndroidSigningKeyPass="${{ secrets.RELEASE_KEYSTORE_PASS }}"
    
    - name: List build output
      shell: bash
      run: ls publish
