name: Build and deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Need full history for git versioning

    - name: Create keystore
      id: create_keystore
      uses: timheuer/base64-to-file@v1.1
      with:
        fileName: 'release.keystore'
        encodedString: "${{ secrets.RELEASE_KEYSTORE_BASE64 }}"

    - uses: actions/setup-dotnet@v2

    - name: Install MAUI workload
      run: dotnet workload install maui-android

    - name: Publish Android project
      run: >
        dotnet publish -c:Release -o "publish"
        -f:net6.0-android
        -p:AndroidKeyStore=True
        -p:AndroidSigningKeyStore="${{ steps.create_keystore.outputs.filePath }}"
        -p:AndroidSigningStorePass="${{ secrets.RELEASE_KEYSTORE_PASS }}"
        -p:AndroidSigningKeyAlias="key"
        -p:AndroidSigningKeyPass="${{ secrets.RELEASE_KEYSTORE_PASS }}"
    
    - uses: actions/upload-artifact@v3
      with:
        path: "publish/*.aab"

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          "publish/*.aab"

    - name: Upload to Play Store
      uses: r0adkll/upload-google-play@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        serviceAccountJsonPlainText: "${{ secrets.SERVICE_ACCOUNT_JSON }}"
        packageName: com.danielchalmers.journalapp
        releaseFiles: "publish/*-Signed.aab"
        track: internal
