name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  android:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Need full history for git versioning

    - name: Create keystore
      id: create_keystore
      uses: timheuer/base64-to-file@v1.1
      with:
        fileName: 'release.keystore'
        encodedString: "${{ secrets.RELEASE_KEYSTORE_BASE64 }}"

    - uses: actions/setup-dotnet@v3
    
    - name: Show .NET info
      run: dotnet --info

    - name: Install .NET MAUI
      run: dotnet workload install maui android wasm-tools

    - name: Build for Android
      run: >
        dotnet publish -c:Release -o "publish"
        -f:net7.0-android
        -p:AndroidKeyStore=True
        -p:AndroidSigningKeyStore="${{ steps.create_keystore.outputs.filePath }}"
        -p:AndroidSigningStorePass="${{ secrets.RELEASE_KEYSTORE_PASS }}"
        -p:AndroidSigningKeyAlias="key"
        -p:AndroidSigningKeyPass="${{ secrets.RELEASE_KEYSTORE_PASS }}"
    
    - uses: actions/upload-artifact@v3
      with:
        path: "publish/*.aab"

#    - name: Create GitHub release
#      uses: softprops/action-gh-release@v1
#      with:
#        files: |
#          "publish/*.aab"
#        generate_release_notes: true

    - name: Upload to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: "${{ secrets.SERVICE_ACCOUNT_JSON }}"
        packageName: com.danielchalmers.journalapp
        releaseFiles: "publish/*-Signed.aab"
        track: internal
        status: draft
