name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  upload-android:
    steps:
    - uses: ./.github/workflows/build.yml

    - uses: softprops/action-gh-release@v1
      with:
        files: |
          "publish/*.aab"

    - uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ SERVICE_ACCOUNT_JSON }}
        packageName: com.danielchalmers.journalapp
        releaseFiles: "publish/*-Signed.aab"
        track: internal
