name: Release

on:
  push:
    tags:
      - "v*.*"

jobs:
  upload-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Need full history for git versioning

    - uses: ./.github/workflows/build.yml

    - uses: softprops/action-gh-release@v1
      with:
        files: |
          "publish/*.aab"

    - uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: "${{ secrets.SERVICE_ACCOUNT_JSON }}"
        packageName: com.danielchalmers.journalapp
        releaseFiles: "publish/*-Signed.aab"
        track: internal
